import uniqid from "uniqid"
import { createSlice } from '@reduxjs/toolkit'
import slugify from "slugify"

import type { GameState, Story } from "~/app/interfaces"

const initialState : GameState = {
	name: "",
	stories: {}
};

// NOTE: Leaving this chunk as a comment for later use
//
// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
// export const incrementAsync = createAsyncThunk(
//   'counter/fetchCount',
//   async (amount) => {
//     const response = await fetchCount(amount);
//     // The value we return becomes the `fulfilled` action payload
//     return response.data;
//   }
// );

export const gameSlice = createSlice({
	name: "game",
	initialState,
	reducers: {
		makeStory(state, action) {
			const payload: Story = action.payload;
			const id = payload.id || uniqid();
			const name = payload.name || "";
			const slug = slugify(name);

			if (!name?.length) {
				throw new Error("Stories must have a name string property.")
			}
			
			state.stories[slug] = {
				id,
				name,
				slug,
				quests: {},
				...action.payload
			};
		},

		setStory(state, action) {
			const payload: Story = action.payload;
			state.stories[payload.slug] = payload;
		},

		updateStory(state, action) {
			const payload: Story = action.payload;
			let story = state.stories[payload.slug];
			if (!story.name?.length) {
				throw new Error("Stories must have a name string property.")
			}
			
			state.stories[payload.slug] = {
				...story,
				...payload
			};
		},

		deleteStory(state, action) {
			delete state.stories[action.payload];
		},

		makeQuest(state, action) {
			const quest = action.payload;
			const id = quest.id || uniqid();
			const name = quest.name || "";
			const slug = slugify(name);
			state.stories[quest.story].quests[slug] = {
				id,
				name,
				slug,
				...quest
			};
		}
	},

	// NOTE: for later
	//
	// The `extraReducers` field lets the slice handle actions defined elsewhere,
	// including actions generated by createAsyncThunk or in other slices.
	// extraReducers: (builder) => {
	//   builder
	//     .addCase(incrementAsync.pending, (state) => {
	//       state.status = 'loading';
	//     })
	//     .addCase(incrementAsync.fulfilled, (state, action) => {
	//       state.status = 'idle';
	//       state.value += action.payload;
	//     });
	// },
});

export const {
	makeStory, setStory, updateStory, deleteStory,
	makeQuest
} = gameSlice.actions;

// NOTE: for later
//
// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
// export const selectCount = (state) => state.counter.value;

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd = (amount) => (dispatch, getState) => {
//   const currentValue = selectCount(getState());
//   if (currentValue % 2 === 1) {
//     dispatch(incrementByAmount(amount));
//   }
// };

export default gameSlice.reducer;
